---
fail_fast: false
repos:
  - hooks:
      - args: [ --fix ]
        id: ruff-check
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
  - hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-xml
      - id: check-toml
      - args: ["--autofix", "--indent=4"]
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
  - hooks:
      - id: uv-lock
      - id: uv-export
    repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.12
  - hooks:
      - id: gitleaks
        name: ğŸ”’ security Â· Detect hardcoded secrets
    repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
  - hooks:
      - additional_dependencies:
          - validate-pyproject-schema-store[all]
        id: validate-pyproject
        name: ğŸ python Â· Validate pyproject.toml
    repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
