---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.3.0
    hooks:
      - id: validate_manifest
        name: ğŸ› ï¸ pre-commit Â· Validate pre-commit configuration
  - hooks:
      - id: check-case-conflict
        name: ğŸ› ï¸ pre-commit Â· Check for case conflicts
      - id: check-merge-conflict
        name: ğŸ› ï¸ pre-commit Â· Check for merge conflicts
      - id: check-yaml
        name: ğŸ› ï¸ pre-commit Â· Check YAML files
      - id: end-of-file-fixer
        name: ğŸ› ï¸ pre-commit Â· Fix end of file
      - id: mixed-line-ending
        name: ğŸ› ï¸ pre-commit Â· Check mixed line endings
      - id: trailing-whitespace
        name: ğŸ› ï¸ pre-commit Â· Check trailing whitespace
      - id: check-json
        name: ğŸ› ï¸ pre-commit Â· Check JSON files
      - id: check-added-large-files
        name: ğŸ› ï¸ pre-commit Â· Check for large files
      - id: check-xml
        name: ğŸ› ï¸ pre-commit Â· Check XML files
      - id: check-toml
        name: ğŸ› ï¸ pre-commit Â· Check TOML files
      - args: ["--autofix", "--indent=4"]
        name: ğŸ› ï¸ pre-commit Â· Check and fix JSON files
        id: pretty-format-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
  - hooks:
      - id: gitleaks
        name: ğŸ”’ security Â· Detect hardcoded secrets
    repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
  - hooks:
      - additional_dependencies:
          - validate-pyproject-schema-store[all]
        id: validate-pyproject
        name: ğŸ validate-pyproject Â· Validate pyproject.toml
    repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        name: ğŸ docformatter Â· Format docstrings
        additional_dependencies: [tomli]
        args: [--in-place, --config, ./pyproject.toml]
  - repo: https://github.com/myint/eradicate
    rev: 3.0.0
    hooks:
      - id: eradicate
        args: []
        name: ğŸ eradicate Â· Remove dead code
  - hooks:
      - args: [ --fix , --config, ./pyproject.toml , --fix-only]
        id: ruff-check
        name: ğŸ ruff Â· Check Python code
      - id: ruff-format
        name: ğŸ ruff Â· Format Python code
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
  - hooks:
      - id: uv-lock
        name: ğŸ uv Â· Lock dependencies
      - id: uv-export
        name: ğŸ uv Â· Export dependencies to pip format
    repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.15
