line-length    = 88
target-version = "py310"

[lint]
    exclude = ["examples"]
    ignore  = ["COM", "D203", "D211", "D213"]
    select  = ["ALL"]

    [lint.per-file-ignores]
        "examples/*" = ["INP001"]
        "examples/test_target.py" = ["F821"]
        "scripts/*.py" = ["S101", "T201", "INP001"]
        "src/debug_dojo/_installers.py" = [
            "PLC0415",
            "T100",
        ]
        "tests/*" = ["S101", "T201"]
        "tests/assets/*" = ["T201", "INP001", "F821"]

[format]
    docstring-code-format = true
