name: Package Tests

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: ğŸ Python Tests and Code Quality

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
    - name: ğŸ› ï¸ Check out the repository
      uses: actions/checkout@v5

    - name: ğŸ› ï¸ Install uv and use Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
       python-version: ${{ matrix.python-version }}

    - name: ğŸ› ï¸ Install the project dependencies
      id: uv-sync
      run: uv sync --locked --all-extras --dev

    # Use poe to sync local checks with CI
    - name: ğŸ Run ruff linter check
      if: always()
      run: uv run poe lint --output-format=github

    - name: ğŸ Run ruff formatter check
      if: always()
      run: uv run poe format

    - name: ğŸ Run basedpyright type checker
      if: always()
      run: uv run poe type-check

    - name: ğŸ Run pytest
      if: always()
      run: uv run poe test


  check:
    name: ğŸ› ï¸ Check if all jobs succeeded

    if: always()
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
